import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import PostCard from '../components/PostCard'
import {MediumContext} from '../context/MediumContext'
import {useContext} from 'react'

export default function Home() {
  const { posts } = useContext(MediumContext);

  const styles = {
    postsList: 'flex flex-col gap-3 p-2 sm:grid-cols-2 md:gap-6 md:p-6 lg:grid-cols-3',
    container: 'max-w-7xl flex-1',
    main: 'flex justify-center',
    wrapper: 'mx-auto'
  }

  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Medium Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <div className={styles.main}>
        <div className={styles.container}>
          <div className={styles.postsList}>

            {posts.map(post => (
              <PostCard post={post} key={post.id} />
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
